# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='profile',
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='beta.User'),
            preserve_default=False,
        ),
    ]
