# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_auto_20180424_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
